BHQ_TC2016_2017_0001/PointPackage/Controllers/PatientSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Linq;
using PointPackage.Models;
using DBCheckup;

namespace PointPackage.Controllers
{
    public class PatientSearchController : Controller
    {
        [HttpGet]
        public ActionResult Main()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Main(PatientSearchModel model)
        {
            try
            {
                using (InhCheckupDataContext cdc = new InhCheckupDataContext())
                {
                    PatientInformationModel pi = new PatientInformationModel();
                    pi.queue_no = model.queue_no;
                    pi.listPatientInformation = cdc.trn_patient_regis
                                                   .Where(x => x.tpr_queue_no == model.queue_no)
                                                   .Select(x => new PatientInformation
                                                   {
                                                       tpr_id = x.tpr_id,
                                                       name = x.trn_patient.tpt_first_name,
                                                       lastname = x.trn_patient.tpt_last_name,
                                                       hn = x.trn_patient.tpt_hn_no,
                                                       en = x.tpr_en_no,
                                                       arrived_date = x.trn_patient_regis_detail == null ? x.tpr_arrive_date.Value : x.trn_patient_regis_detail.tpr_real_arrived_date.Value
                                                   }).OrderByDescending(x => x.arrived_date)
                                                   .ToList();
                    if (pi.listPatientInformation.Count == 0)
                    {
                        ViewBag.QueueNo = model.queue_no + " is Not Found.";
                        ModelState.Clear();
                        return View("Main", new PatientSearchModel());
                    }
                    else
                    {
                        ViewBag.QueueNo = model.queue_no;
                        return View("PatientList", pi);
                    }
                }
            }
            catch
            {
                ViewBag.PageTitle = "Error (Please Try Again)";
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult PatientList(PatientInformationModel model)
        {
            return View("Main");
        }

        [HttpPost]
        public ActionResult PatientList(int tpr_id, string queue_no)
        {
            ViewBag.QueueNo = queue_no;
            return View("SelectAction", new SelectActionModel() { queue_no = queue_no, tpr_id = tpr_id });
        }

        [HttpGet]
        public ActionResult SelectAction(SelectActionModel model)
        {
            return View("Main");
        }

        [HttpPost]
        public ActionResult SelectAction(int tpr_id, string queue_no, int action)
        {
            switch (action)
            {
                case 1:
                    using (InhCheckupDataContext cdc = new InhCheckupDataContext())
                    {
                        ViewPackageModel vp = new ViewPackageModel() { queue_no = queue_no, tpr_id = tpr_id };
                        vp.listPackage = cdc.trn_patient_order_sets
                                            .Where(x => x.tpr_id == tpr_id)
                                            .Select(x => new Package
                                            {
                                                package_code = x.tos_od_set_code,
                                                package_name = x.tos_od_set_name
                                            }).ToList();
                        ViewBag.QueueNo = queue_no;
                        return View("ViewPackage", vp);
                    }
                case 2:
                    using (InhCheckupDataContext cdc = new InhCheckupDataContext())
                    {
                        ViewBag.QueueNo = queue_no;
                        var dummyModel = new AddDummyModel() { queue_no = queue_no, tpr_id = tpr_id };
                        ViewBag.selectpackage = cdc.mst_order_points
                                                   .Where(x => x.mot_set_code.StartsWith("GHOSTPACK"))
                                                   .Select(x => new SelectListItem
                                                   {
                                                       Text = x.mot_set_name,
                                                       Value = x.mot_set_code
                                                   }).ToList();
                        return View("AddDummyPackage", new AddDummyModel() { queue_no = queue_no, tpr_id = tpr_id });
                    }
                case 3:
                    try
                    {
                        using (InhCheckupDataContext cdc = new InhCheckupDataContext())
                        {
                            List<trn_patient_order_set> listSet = cdc.trn_patient_order_sets
                                                                     .Where(x => x.tpr_id == tpr_id)
                                                                     .ToList();
                            listSet.ForEach(x => x.tos_status = null);
                            cdc.SubmitChanges();
                        }
                        return View("ResultPage", new ResultPageModel() { queue_no = queue_no, messege = "Cancel Package Queue No." + queue_no + " successful." });
                    }
                    catch
                    {
                        return View("ResultPage", new ResultPageModel() { queue_no = queue_no, messege = "Cancel Package Queue No." + queue_no + " not successful." });
                    }
                default:
                    return View("SelectAction", tpr_id);
            }
        }

        

        [HttpGet]
        public ActionResult ViewPackage(ViewPackageModel model)
        {
            return View("Main");
        }

        [HttpPost]
        public ActionResult ViewPackage(string queue_no, int tpr_id, string package_code)
        {
            string package_name = getPackageName(package_code);
            ViewBag.QueueNo = queue_no;
            ViewBag.selectpoint = new List<SelectListItem>
                                  {
                                      new SelectListItem { Text = "2.0", Value = "2.0" },
                                      new SelectListItem { Text = "1.5", Value = "1.5" },
                                      new SelectListItem { Text = "1.0", Value = "1.0" },
                                      new SelectListItem { Text = "0.5", Value = "0.5" }
                                  };
            return View("AddMasterPackage", new AddMasterPackageModel() { queue_no = queue_no, tpr_id = tpr_id, package_code = package_code, package_name = package_name , point = 0 });
        }

        [HttpGet]
        public ActionResult AddDummyPackage(AddDummyModel model)
        {
            return View("Main");
        }

        [HttpPost]
        public ActionResult AddDummyPackage(string queue_no, int tpr_id, string packagecode)
        {
            try
            {
                using (InhCheckupDataContext cdc = new InhCheckupDataContext())
                {
                    DateTime dateNow = DateTime.Now;
                    var package = cdc.mst_order_points
                                     .Where(x => x.mot_set_code == packagecode &&
                                                 x.mot_status == 'A')
                                     .Select(x => new
                                     {
                                         x.mot_set_code,
                                         x.mot_set_name
                                     }).FirstOrDefault();
                    if (package != null)
                    {
                        cdc.trn_patient_order_sets.InsertOnSubmit(new trn_patient_order_set
                        {
                            tpr_id = tpr_id,
                            tos_create_by = "PointProj",
                            tos_create_date = dateNow,
                            tos_od_set_code = package.mot_set_code,
                            tos_od_set_name = package.mot_set_name,
                            tos_status = true,
                            tos_update_by = "PointProj",
                            tos_update_date = dateNow
                        });
                        ViewBag.QueueNo = queue_no;
                        cdc.SubmitChanges();
                        return View("ResultPage", new ResultPageModel() { queue_no = queue_no, messege = "Add Package " + package.mot_set_name + " successful." });
                    }
                    else
                    {
                        ViewBag.QueueNo = queue_no;
                        return View("ResultPage", new ResultPageModel() { queue_no = queue_no, messege = "Error : Package Dummy is not found." });
                    }
                }
            }
            catch
            {
                ViewBag.QueueNo = queue_no;
                return View("ResultPage", new ResultPageModel() { messege = "Error : Please Try Again." });
            }
        }

        [HttpGet]
        public ActionResult AddMasterPackage(AddMasterPackageModel model)
        {
            return View("Main");
        }

        [HttpPost]
        public ActionResult AddMasterPackage(string queue_no, int tpr_id, string package_code, double point)
        {
            try
            {
                string package_name = getPackageName(package_code);
                using (InhCheckupDataContext cdc = new InhCheckupDataContext())
                {

BHQ_TC2016_2017_0001/PointPackage/Views/PatientSearch/AddDummyPackage.cshtml
@model PointPackage.Models.AddDummyModel
@{
    Layout = "~/Views/PatientSearch/_MasterPatientSearch.cshtml";
}

<script type="text/javascript">
    window.onload = function () {
        var form = document.getElementById("AddDummyPackage");
        form.addEventListener('submit', function (e) {
            if ($('#selectpackage').val() == "") {
                alert('Please select package.');
                e.preventDefault();
            }
            else {
                var strConfirm = "Do you want to add package : " + $('#selectpackage :selected').text(); +"?";
                if (confirm(strConfirm) == false) {
                    e.preventDefault();
                }
                else {
                    $('#packagecode').val($('#selectpackage').val());
                }
            }
        });
    }
</script>
@using (Html.BeginForm("AddDummyPackage", "PatientSearch", FormMethod.Post, new { id = "AddDummyPackage" }))
{
    @Html.HiddenFor(x => x.tpr_id)
    @Html.HiddenFor(x => x.queue_no)
    @Html.Hidden("packagecode", new { @id = "packagecode" })
    <div class="row">
        <div class="12u$">
            <article class="item">
                <h4 style="text-align:left; padding-bottom:15px;">Please Insert Point of Dummy Package :</h4>
                @*@Html.TextBoxFor(x => x.point, new { @style = "margin-bottom:1em; margin-top:1em;" })*@
                @Html.DropDownList("selectpackage", "select package.")
                <input style="margin-top:15px;" type="submit" value="Submit." />
            </article>
        </div>
    </div>
}

BHQ_TC2016_2017_0001/PointPackage/Views/PatientSearch/AddMasterPackage.cshtml
@model PointPackage.Models.AddMasterPackageModel
@{
    Layout = "~/Views/PatientSearch/_MasterPatientSearch.cshtml";
}

<script type="text/javascript">
    window.onload = function () {
        var form = document.getElementById("AddMasterPackage");
        form.addEventListener('submit', function (e) {
            if ($('#selectpoint').val() == "") {
                alert('Please select point.');
                e.preventDefault();
            }
            else {
                var strConfirm = "Do you want to add point " + $('#selectpoint :selected').text() + "?";
                if (confirm(strConfirm) == false) {
                    e.preventDefault();
                }
                else {
                    $('#point').val($('#selectpoint').val());
                }
            }
        });
    }
</script>
@using (Html.BeginForm("AddMasterPackage", "PatientSearch", FormMethod.Post, new { id = "AddMasterPackage" }))
{
    @Html.HiddenFor(x => x.queue_no)
    @Html.HiddenFor(x => x.tpr_id)
    @Html.HiddenFor(x => x.package_code)
    @Html.Hidden("point", new { @id = "point" })
    <div class="row">
        <div class="12u$">
            <article class="item">
                <h4 style="text-align:left;">Package Code : @Model.package_code</h4>
                <h4 style="text-align:left; padding-bottom:15px;">Package Name : @Model.package_name</h4>
                @*@Html.TextBoxFor(x => x.point, new { @style = "margin-bottom:1em; margin-top:1em;" })*@
                @Html.DropDownList("selectpoint", "select point.")
                <input style="margin-top:15px;" type="submit" value="Submit." />
            </article>
        </div>
    </div>
}

BHQ_TC2016_2017_0001/PointPackage/Views/PatientSearch/Main.cshtml
@model PointPackage.Models.PatientSearchModel
@{
    Layout = "~/Views/PatientSearch/_MasterPatientSearch.cshtml";
}
@using (Html.BeginForm("Main", "PatientSearch", FormMethod.Post, new { id = "Main" }))
{
    <div class="12u$" style="padding-bottom:1em;">
        @Html.TextBoxFor(x => x.queue_no, new { placeholder = "Queue No." })
    </div>
    <div class="12u$">
        <input type="submit" value="Next.">
    </div>
}

BHQ_TC2016_2017_0001/PointPackage/Views/PatientSearch/PatientList.cshtml
@model PointPackage.Models.PatientInformationModel
@{
    Layout = "~/Views/PatientSearch/_MasterPatientSearch.cshtml";
}

<script type="text/javascript">
    function clickPatient(tpr_id) {
        $('#tpr_id').val(tpr_id);
        $('#PatientList').submit();
    }
</script>
@using (Html.BeginForm("PatientList", "PatientSearch", FormMethod.Post, new { id = "PatientList" }))
{
    @Html.HiddenFor(x => x.queue_no)
    @Html.Hidden("tpr_id", new { @id = "tpr_id" })
    <div class="row">
        @for (var i = 0; i < Model.listPatientInformation.Count; i++)
        {
            <div class="4u 12u$(mobile)">
                <article class="item" onclick="clickPatient(@Model.listPatientInformation[i].tpr_id)" style="cursor:pointer;">
                    <header style="padding:15px 15px 15px 15px;">
                        <h3 style="text-align:left;">HN : @Model.listPatientInformation[i].hn</h3>
                        <h3 style="text-align:left;">EN : @Model.listPatientInformation[i].en</h3>
                        <h3 style="text-align:left;">Name : @Model.listPatientInformation[i].name</h3>
                        <h3 style="text-align:left;">Lastname : @Model.listPatientInformation[i].lastname</h3>
                        <h3 style="text-align:left;">Arrived Date : @Model.listPatientInformation[i].arrived_date.ToString("dd/MM/yyyy")</h3>
                        <h3 style="text-align:left;">Arrived Time : @Model.listPatientInformation[i].arrived_date.ToString("HH:mm:ss")</h3>
                    </header>
                </article>
            </div>
        }
    </div>
}

BHQ_TC2016_2017_0001/PointPackage/Views/PatientSearch/ResultPage.cshtml
@model PointPackage.Models.ResultPageModel
@{
    Layout = "~/Views/PatientSearch/_MasterPatientSearch.cshtml";
}

@using (Html.BeginForm("ResultPage", "PatientSearch", FormMethod.Post, new { id = "ResultPage" }))
{
    @Html.DisplayFor(x => x.messege)
}

BHQ_TC2016_2017_0001/PointPackage/Views/PatientSearch/SelectAction.cshtml
@model PointPackage.Models.SelectActionModel
@{
    Layout = "~/Views/PatientSearch/_MasterPatientSearch.cshtml";
}

<script type="text/javascript">
    function clickAction(action) {
        if (action == 3) {
            if (confirm("Do you want to cancel package?") == false) {
                return;
            }
        }
        $('#action').val(action);
        $('#SelectAction').submit();
    }
</script>
@using (Html.BeginForm("SelectAction", "PatientSearch", FormMethod.Post, new { id = "SelectAction" }))
{
    @Html.HiddenFor(x => x.queue_no)
    @Html.HiddenFor(x => x.tpr_id)
    @Html.Hidden("action", new { @id = "action" })
    <div class="row">
	    <div class="6u 12u$(mobile)"><input type="button" value="Add Master Package." onclick="clickAction(1)" /></div>
        <div class="6u$ 12u$(mobile)"><input type="button" value="Add Dummy Package." onclick="clickAction(2)" /></div>
	    <div class="6u 12u$(mobile)"><input type="button" value="Cancel Package." onclick="clickAction(3)" /></div>
    </div>
}

BHQ_TC2016_2017_0001/PointPackage/Views/PatientSearch/ViewPackage.cshtml
@model PointPackage.Models.ViewPackageModel
@{
    Layout = "~/Views/PatientSearch/_MasterPatientSearch.cshtml";
}

<script type="text/javascript">
    function clickPackage(package_code) {
        $('#ViewPackage').append('<input type="hidden" name="package_code" value=' + package_code + ' />');
        $('#ViewPackage').submit();
    }
</script>
@using (Html.BeginForm("ViewPackage", "PatientSearch", FormMethod.Post, new { id = "ViewPackage" }))
{
    @Html.HiddenFor(x => x.queue_no)
    @Html.HiddenFor(x => x.tpr_id)
    <div class="row">
        @for (var i = 0; i < Model.listPackage.Count; i++)
        {
            <div class="12u$">
                <article class="item" onclick="clickPackage('@Model.listPackage[i].package_code');" style="cursor:pointer;">
                    <header align="left" style="padding:15px 15px 15px 15px;">
                        <h3>Package Code : @Model.listPackage[i].package_code</h3>
                        <h3>Package Name : @Model.listPackage[i].package_name</h3>
                    </header>
                </article>
            </div>
        }
    </div>
}

BHQ_TC2016_2017_0001/PointPackage/Views/PatientSearch/_MasterPatientSearch.cshtml
@{
    ViewBag.Title = "Add point manual.";
    Layout = "~/Views/Shared/_MasterPage.cshtml";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#sectionHeader').css('width', $('#main').css('width'));
        var detailMarginTop = document.getElementById('sectionHeader').offsetTop + document.getElementById('sectionHeader').offsetHeight;
        $('#sectionDetail').css('margin-top', detailMarginTop + 'px');
    });

    $(window).resize(function () {
        $('#sectionHeader').css('width', $('#main').css('width'));
        var queueMarginTop = document.getElementById('sectionHeader').offsetTop + document.getElementById('sectionHeader').offsetHeight;

        $('#sectionQueue').css('width', $('#main').css('width'));
        $('#sectionQueue').css('margin-top', queueMarginTop + 'px');

        var detailMarginTop = queueMarginTop + document.getElementById('sectionQueue').offsetHeight;
        $('#sectionDetail').css('margin-top', detailMarginTop + 'px');
    });


</script>
<div id="main">
    <section id="sectionHeader" class="two" style="top:0px; right:0; position:fixed; display:block; padding:9px;">
        <header>
            <h2 style="text-align:right">Add point manual</h2>
        </header>
    </section>
    <section id="sectionQueue" class="three" style="top:0px; right:0; position:fixed; display:block; padding:9px;">
        <header>
            <h4>Queue No : @ViewBag.QueueNo</h4>
        </header>
    </section>
    <section id="sectionDetail" class="four" style="padding:1em; overflow:visible;">
        <div class="container">
            @RenderBody()
        </div>
    </section>
</div>